version: "3.7"

networks:
  electronicboard-net:
    driver: bridge

services:
  api:
    build:
      context: .
      dockerfile: Backend/ElectronicBulletinBoard/src/ElectronicBoard/Hosts/ElectronicBoard.Api/Dockerfile
    ports:
      - 7097:7097
    environment:
      - DOTNET_RUNNING_IN_CONTAINER=true
      - ASPNETCORE_URLS=http://+:7097
    depends_on:
      - "postgres"
      - "rabbitmq"
    networks:
      - electronicboard-net
      
  web:
    build:
      context: .
      dockerfile: UI/Dockerfile
    ports:
      - 80:80
    networks:
      - electronicboard-net
      
  emailservice:
    build:
      context: .
      dockerfile: Backend/EBoardEmailService/EBoardEmailService/Dockerfile
    depends_on:
      - "rabbitmq"
    networks:
      - electronicboard-net

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    networks:
      - electronicboard-net

  postgres:
    image: "postgres"
    restart: always
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "ElectronicBoard"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - electronicboard-net

volumes:
  postgres_data: